import './globals.css';
import { Providers } from './providers/providers';

export const metadata = {
  title: 'CasaVerde | Home',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-background bg-cover">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
